# Available parameters and their default values to this chart.

# ==============================================================================
# GLOBAL DEFINITION
# ==============================================================================

# Legend:
#   - group: GitLab Group Reference.
#   - subGroup: GitLab Sub Group Reference.
#   - client: Client name.
#   - replicaCount: Number of replicas of the deployment.
#   - environment: Cluster Environment.
#   - domain: Your Domain.
#   - image.tag: GitLab Image Tag Reference.
#   - image.pullPolicy: Update image policies.
#   - image.pullSecrets: Registration key for a pod - It would be a secret to our registration.
#   - image.registry: Your Registry.
#
global:
  group: msp
  subGroup: mcms
  client: mspcel430
  replicaCount: 1
  environment: stage
  domain: domain.io
  image:
    tag: develop
    pullPolicy: IfNotPresent
    pullSecrets: secret-key
    registry: registry.io

# ==============================================================================
# SERVICE DEFINITION
# ==============================================================================

service:
  type: ClusterIP
  port: 80
  targetPort: 9106
  annotations: {}
  labels: {}

# ==============================================================================
# RESOURCES DEFINITION
# ==============================================================================

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: {}
  # limits:
  #   cpu: 200m
  #    memory: 252Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# ==============================================================================
# LIVENESS AND READINESS PROBE DEFINITION
# ==============================================================================
    
# Configurable health checks against the /healthy and /ready endpoints
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# ==============================================================================
# SECURITY CONTEXT DEFINITION
# ==============================================================================

securityContext:
  runAsUser: 65534  # run as nobody user instead of root

# ==============================================================================
# NGINX DEFINITION
# ==============================================================================

nginx:
  auth:
    type: basic
    secret:
      name: basic-auth
      user: admin-cloud
      password:
    realm: Auth Required - Monitoring

# ==============================================================================
# PROVIDERS DEFINITION
# ==============================================================================

providers:
  aws:
    accessKey:
    secretKey:
    exporters:
      - name: lambda
        enabled: true
        config: |-
          ---
          region: us-east-1
          metrics:

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: Invocations
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: Errors
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: DeadLetterErrors
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: DestinationDeliveryFailures
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: Throttles
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: ProvisionedConcurrencyInvocations
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]

          # LAMBDA
          - aws_namespace: AWS/LAMBDA
            aws_metric_name: ProvisionedConcurrencySpilloverInvocations
            aws_dimensions: [FunctionName]
            aws_statistics: [Sum]
      - name: billing
        enabled: true
      - name: ebs
        enabled: true
      - name: elasticache
        enabled: true
      - name: vpn
        enabled: true
      - name: ses
        enabled: false
      - name: sqs
        enabled: false
      - name: rds
        enabled: true
      - name: elb
        enabled: true
  google:
    exporters:
  azure:
    exporters:
