{{- if .Values.providers.aws.exporters }}
{{- range .Values.providers.aws.exporters }}
---
{{- if and .enabled .config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-configmap
data:
  config.yml: |-
{{ .config | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
---
