{{- if and (.Files.Glob "files/exporters/*.{yml,yaml}") .Values.providers.aws.exporters }}
{{- $globalPath := .Files.Glob "files/exporters/*.{yml,yaml}" }}
{{- range .Values.providers.aws.exporters }}
{{- $name := .name }}
{{- if and .enabled (not (.config)) }}
{{- range $path, $bytes := $globalPath }}
{{- $file := base $path | replace ".yml" "" | replace ".yaml" "" }}
{{- if eq $file $name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $file }}-external-configmap
data:
  config.yml: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
---
