{{- $apiVersion := include "ingress.apiVersion" . -}}
{{- $port := default 80 .Values.service.port -}}
{{- $client := default 80 .Values.global.client -}}
{{- $environment := default 80 .Values.global.environment -}}
{{- $domain := default 80 .Values.global.domain -}}
{{- $nginxAuthType := .Values.nginx.auth.type -}}
{{- $nginxAuthSecret := .Values.nginx.auth.secret.name -}}
{{- $nginxAuthRealm := .Values.nginx.auth.realm -}}
{{- if .Values.providers.aws.exporters }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: ingress-api-metrics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: {{ $nginxAuthType }}
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: {{ $nginxAuthSecret }}
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: {{ $nginxAuthRealm }}
spec:
  rules:
    - host: {{ $client }}-cloud-mcms.{{ $environment }}.{{ $domain }}
      http:
        paths:
        {{- range .Values.providers.aws.exporters }}
        {{- if .enabled }}
          - path: /api/aws/{{ .name }}/?(.*)
            backend:
              serviceName: {{ .name }}
              servicePort: {{ $port }}
        {{- end }}
        {{- end }}
{{- end }}
---
{{- if .Values.providers.aws.exporters }}
{{- range .Values.providers.aws.exporters }}
{{- if .enabled }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: ingress-{{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: {{ $nginxAuthType }}
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: {{ $nginxAuthSecret }}
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: {{ $nginxAuthRealm }}
spec:
  rules:
    - host: {{ $client }}-msp-mcms-api-aws-{{ .name }}.{{ $environment }}.{{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .name }}
              servicePort: {{ $port }}
{{- end }}
{{- end }}
{{- end }}