apiVersion: v1
data:
  .dockerconfigjson: 
kind: Secret
metadata:
  name: {{ .Values.global.image.pullSecrets }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aws.secret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "aws.secret.name" . }}
type: Opaque
data:
  aws-access-key: {{ include "aws.access.key" . }}
  aws-secret-key: {{ include "aws.secret.key" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.auth.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.nginx.auth.secret.name }}
type: Opaque
data:
  auth: {{ include "nginx.auth.secret.password" . }}
---
