{{- $chartName := include "project-mcms.chart" . -}}
{{- $chartVersion := .Chart.AppVersion -}}

{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $releaseNamespace := .Release.Namespace -}}

{{- $type := default "ClusterIP" .Values.service.type -}}
{{- $port := default 80 .Values.service.port -}}
{{- $targetPort := default 9106 .Values.service.targetPort -}}

{{- if .Values.providers.aws.exporters }}
{{- range .Values.providers.aws.exporters }}
---
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $releaseNamespace }}
  labels:
    helm.sh/chart: {{ $chartName }}
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
    {{- if $chartVersion }}
    app.kubernetes.io/version: {{ $chartVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  type: {{ $type }}
  ports:
    - name: {{ .name }}
      port: {{ $port }}
      protocol: TCP
      targetPort: {{ $targetPort }}
  selector:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $releaseName }}
{{- end }}
{{- end }}
{{- end }}
---
